config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  post "photos/preview", to: "photos#preview", as: :preview_photo
  resources :photos, only: [:index, :create] do
    get :download, on: :member
  end
  get "tour-dates", to: "home#tour_dates"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  PER_REQUEST = 10

  mount_uploader :image, ImageUploader

  attr_accessor :color

  validates_presence_of :creator_email, :image

  scope :gallery, -> { where(gallery: true) }
  scope :most_recent, -> { order(created_at: :desc) }
  scope :per_request, -> { limit(PER_REQUEST) }

  def image_cache_url
    "/uploads/tmp/#{self.image_cache}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :find_photos

  private

  def find_photos
    @photos = Photo.gallery.most_recent.per_request
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @photo = Photo.new
  end

  def tour_dates
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_action :find_photos, only: :download
  before_action :initialize_photo, only: [:preview, :create]

  def index
    @photos = @photos.offset(params[:offset].to_i)
  end

  def preview
    if @photo.invalid?
      flash.now[:alert] = "Please enter your email address and pick a photo in one of these formats: #{extension_white_list}"
      render "home/index"
    end
  end

  def create
    if @photo.save
      @photos = @photos.where.not(id: @photo.id)
      flash.now[:notice] = "Thanks for participating! You've been entered into the drawing for a free signed album."
      render :share
    else
      flash.now[:alert] = "Oops! Something went wrong. Please try again."
      render "home/index"
    end
  end

  def download
    @photo = Photo.find(params[:id])
    data = open(@photo.image_url)
    send_data data.read, filename: filename
  end

  private

  def initialize_photo
    @photo = Photo.new(photo_params)
  end

  def photo_params
    params.require(:photo).permit(:creator_email, :image, :image_cache, :color, :gallery)
  end

  def extension_white_list
    @photo.image.extension_white_list.map(&:upcase).join(", ")
  end

  def filename
    timestamp = Time.now.to_s(:number)
    extension = @photo.image.format
    "brand_new_flag_#{timestamp}.#{extension}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def header_has_callout?
    content_for(:header) =~ /callout/
  end

  def order_link options = {}
    options[:class] = "button " + options[:class].to_s

    link_to "https://lastchancerecords.merchtable.com", options do
      fa_icon("angle-double-right") + "Order the Album"
    end
  end

  def star number
    content_tag(:div, class: "star") do
      fa_icon("star") + content_tag(:span, number)
    end
  end

  def facebook_share_link
    query_params = { app_id: AppConfig["facebook_app_id"], href: "http://www.twocowgarage.net" }
    url = "https://www.facebook.com/dialog/share?#{query_params.to_query}"
    share_link(url, "facebook")
  end

  def twitter_share_link
    text = "The new Two Cow Garage album \"Brand New Flag\" is here! @twocowgarage1"
    query_params = { text: text, url: "http://www.twocowgarage.net", hashtags: "TwoCowGarage,BrandNewFlag" }
    url = "https://twitter.com/intent/tweet?#{query_params.to_query}"
    share_link(url, "twitter")
  end

  def share_link url, icon
    link_to url, target: "_blank", class: "button" do
      fa_icon(icon) + "Share"
    end
  end

end

app/views/home/index.html.erb
<% content_for :header do %>
  <iframe src="https://www.youtube-nocookie.com/embed/qxFc_j2kjcc?rel=0&amp;controls=0&amp;showinfo=0"
    frameborder="0" allowfullscreen class="hidden-xs"></iframe>

  <div class="callout">
    <h1>"Brand New Flag"</h1>
    <p>In Stores Now</p>
    <p>Show your support for <b>TCG</b> by creating a custom profile photo.</p>
  </div>

  <%= order_link(class: "hidden-xs") %>

  <div class="social-links hidden-xs">
    <%= link_to "https://www.facebook.com/Two-Cow-Garage-15327419845", target: "_blank" do %>
      <%= fa_icon("facebook-square") %>
    <% end %>
    <%= link_to "https://twitter.com/twocowgarage1", target: "_blank" do %>
      <%= fa_icon("twitter-square") %>
    <% end %>
    <%= link_to "https://www.instagram.com/twocowgarage", target: "_blank" do %>
      <%= fa_icon("instagram") %>
    <% end %>
  </div>
<% end %>

<div class="row">
  <div class="col-sm-7 clearfix">
    <%= form_for @photo, url: preview_photo_path do |f| %>
      <div class="form-group">
        <%= star(1) %>
        <%= fa_icon("check-circle-o") %>
        <%= f.label :creator_email, class: "sr-only" %>
        <%= f.email_field :creator_email, placeholder: "Enter your email address." %>
      </div>

      <div class="form-group">
        <%= star(2) %>
        <%= fa_icon("check-circle-o") %>
        <button type="button" id="image-btn">Pick A Photo</button>
        <%= f.label :image, class: "sr-only" %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>

      <div class="form-group">
        <%= star(3) %>
        <%= f.submit "Pick A Color", class: "disabled" %>
      </div>
    <% end %>
  </div>

  <div class="col-sm-5">
    <div id="example-photo" class="photo hidden-xs"></div>
  </div>
</div>

<script type="text/javascript">
  $("input#photo_creator_email, input#photo_image").change(function() {
    var value = $(this).val();
    if (value) { $(this).siblings("i.fa").fadeIn(300) };
    enableSubmitButton();
  });

  $("button#image-btn").click(function() {
    $("input#photo_image").click();
  });

  function enableSubmitButton() {
    var email = $("input#photo_creator_email").val();
    var image = $("input#photo_image").val();
    if (email && image) { $("input[type='submit']").removeClass("disabled") };
  }
</script>

app/views/home/tour_dates.html.erb
<% content_for :header, order_link(class: "hidden-xs") %>

<h2>Tour Dates</h2>
<div id="tour-dates"></div>

<script type="text/javascript">
  if ($("script#bit-js").length == 0) {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "http://widget.bandsintown.com/javascripts/bit_widget.js";
    script.id = "bit-js";
    script.onload = function() {
      new BIT.Widget({
        artist: "Two Cow Garage",
        text_color: "#555555",
        link_color: "#C1223C",
        separator_color: "#CCCCCC",
        notify_me: false,
        share_links: false,
        div_id: "tour-dates"
      }).insert_events();
    }
    document.getElementsByTagName("head")[0].appendChild(script);
  }
</script>

app/views/layouts/_facebook_js.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<%= AppConfig["facebook_app_id"] %>',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_flash.html.erb
<% flash.each do |name, message| %>
  <div class="alert alert-dismissable flash flash-<%= name %>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <div class="container"><%= message %></div>
  </div>
<% end %>

<script type="text/javascript">
  window.setTimeout(function() {
    $("div.flash").fadeOut(300, function() {
      $(this).alert("close");
    });
  }, 10000);
</script>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= AppConfig["google_analytics_id"] %>', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_open_graph_meta_tags.html.erb
<meta property="og:url"         content="http://www.twocowgarage.net" />
<meta property="og:title"       content="Two Cow Garage | Brand New Flag | In Stores Now" />
<meta property="og:description" content="Show your support for TCG by creating a custom profile photo." />
<meta property="og:site_name"   content="Two Cow Garage" />
<meta property="og:image"       content="http://res.cloudinary.com/dxb4raa6b/image/asset/v1465254313/banner_mini-e850f69c21f3d3cc3dcf6ba956725fe5.jpg" />
<meta property="fb:app_id"      content="<%= AppConfig["facebook_app_id"] %>" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Two Cow Garage</title>
  <meta name="description" content="The official Two Cow Garage website. New album BRAND NEW FLAG in stores now." />
  <%= render "layouts/open_graph_meta_tags" %>
  <%= favicon_link_tag "favicon.png" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Montserrat:700|Source+Sans+Pro:300,400,700" %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <% if Rails.env.production? %>
    <%= render "layouts/google_analytics" %>
  <% end %>
</head>
<body>
  <%= render "layouts/facebook_js" %>
  <%= render "layouts/flash" %>

  <nav>
    <%= link_to "Home", root_path %>
    <%= fa_icon("star") %>
    <%= link_to "Tour Dates", tour_dates_path %>
    <%= fa_icon("star") %>
    <%= link_to "TCG Store", "http://twocowgarage.bigcartel.com" %>
  </nav>

  <div class="container">
    <header class="<%= "mini" unless header_has_callout? %>">
      <%= content_for :header %>
    </header>

    <%= yield %>

    <%= render "photos/gallery", photos: @photos %>
  </div>

  <footer>
    &copy; <%= Time.now.year %> Two Cow Garage
    <br class="visible-xs-block" />
    <%= fa_icon("star", class: "hidden-xs") %>
    Booking: <%= mail_to "tylerrehm@gmail.com", "The TR Agency" %>
  </footer>
</body>
</html>

app/views/photos/_gallery.html.erb
<h2>Gallery</h2>

<div id="gallery" data-offset="<%= Photo::PER_REQUEST %>">
  <%= render @photos %>
</div>

<script type="text/javascript">
  $("div#gallery div.photo").css("opacity", 1);

  $(window).scroll(function() {
    var position = $(window).scrollTop() + $(window).height();

    if (position == $(document).height()) {
      var offset = $("div#gallery").data("offset");

      $.ajax({
        method: "GET",
        url: "<%= photos_path %>",
        data: { offset: offset },
        dataType: "script"
      });
    }
  });
</script>

app/views/photos/_photo.html.erb
<div class="photo" style="background-image: url(<%= photo.image_url %>)"></div>

app/views/photos/index.js.erb
$gallery = $("div#gallery");
$gallery.append("<%=j render @photos %>");

var $photos = $gallery.children("div.photo");
$photos.animate({ opacity: 1 }, 300);

var offset = $gallery.data("offset");
offset = +offset + <%= Photo::PER_REQUEST %>;
$gallery.data("offset", offset);

app/views/photos/preview.html.erb
<% content_for :header, order_link(class: "hidden-xs") %>

<div class="row">
  <div class="col-sm-6">
    <%= form_for @photo, html: { id: "preview-photo", class: "clearfix" } do |f| %>
      <%= f.hidden_field :creator_email %>
      <%= f.hidden_field :image_cache %>
      <%= f.hidden_field :color, value: "red" %>

      <h2>Pick A Color</h2>

      <button type="button" class="selector" data-color="red"></button>
      <button type="button" class="selector" data-color="gold"></button>
      <button type="button" class="selector" data-color="green"></button>
      <button type="button" class="selector" data-color="blue"></button>
      <button type="button" class="selector" data-color="purple"></button>
      <button type="button" class="selector" data-color="grey"></button>

      <div class="checkbox">
        <%= f.label :gallery do %>
          <%= f.check_box :gallery %>
          <%= fa_stacked_icon("check", base: "square-o") %>
          Add photo to the public gallery
        <% end %>
      </div>

      <%= f.submit "Save My Photo" %>
      <div class="separator">- OR -</div>
      <%= link_to "Start Over", root_path, class: "button" %>
    <% end %>
  </div>

  <div class="col-sm-6">
    <div id="photo-preview" class="photo" style="background-image: url(<%= @photo.image_cache_url %>)">
      <%= image_tag "overlay_red.png", class: "overlay red" %>
      <%= image_tag "overlay_gold.png", class: "overlay gold" %>
      <%= image_tag "overlay_green.png", class: "overlay green" %>
      <%= image_tag "overlay_blue.png", class: "overlay blue" %>
      <%= image_tag "overlay_purple.png", class: "overlay purple" %>
      <%= image_tag "overlay_grey.png", class: "overlay grey" %>
    </div>

    <small>
      Photo turned the wrong way?
      Orientation will be corrected automatically when you click "SAVE MY PHOTO".
    </small>
  </div>
</div>

<script type="text/javascript">
  $("button.selector").click(function() {
    var color = $(this).data("color");
    $("img.overlay").not("." + color).css("opacity", 0);
    $("img.overlay." + color).css("opacity", 1);
    $("input#photo_color").val(color);
  });
</script>

app/views/photos/share.html.erb
<% content_for :header, order_link(class: "hidden-xs") %>

<div id="share" class="row">
  <h2>Share Your Photo</h2>

  <div class="col-sm-7 clearfix">
    <div class="step">
      <%= star(1) %>
      <% if browser.device.mobile? %>
        <%= link_to "Download My Photo", @photo.image_url, target: "_blank", class: "button" %>
        This will open your photo in a new browser tab. Hold your finger down on the photo and click "Save Image". Then, close the tab.
      <% else %>
        <%= link_to "Download My Photo", download_photo_path(@photo), class: "button" %>
      <% end %>
    </div>

    <h3>For Facebook:</h3>
    <div class="step">
      <%= star(2) %>
      Log into your <%= link_to "Facebook", "https://www.facebook.com", target: "_blank" %> account, go to your profile page, and click the camera icon in the corner of your profile photo.
    </div>
    <div class="step">
      <%= star(3) %>
      Click "Upload Photo" and select the photo you just downloaded. It should look like brand_new_flag_20160605094226.png. Then, click "Save".
    </div>

    <h3>For Twitter:</h3>
    <div class="step">
      <%= star(2) %>
      Log into your <%= link_to "Twitter", "https://twitter.com", target: "_blank" %> account, go to your profile page, and click the "Edit profile" button on the right side of the page.
    </div>
    <div class="step">
      <%= star(3) %>
      Click your profile photo, choose "Upload photo", and select the photo you just downloaded. It should look like brand_new_flag_20160605094226.png. Then, click "Apply".
    </div>
  </div>

  <div class="col-sm-5">
    <div class="photo" style="background-image: url(<%= @photo.image_url %>)"></div>
    <div class="share-links">
      <%= facebook_share_link %>
      <%= twitter_share_link %>
    </div>
    <%= link_to "Create Another Photo", root_path, class: "button" %>
  </div>
</div>